package com.example.itemlist;

import java.util.ArrayList;

public class FootballData {
    private static String[] title = new String[]{
            "Lionel Messi", "Robert Lewandowski", "Gerard Moreno", "Neymar Jr", "Jadon Sancho",
            "John Stones", "Kylian Mbappé", "Iago Aspas", "Joao Cancelo", "Nico Elvedi"
    };

    private static int[] thumbnail = new int[]{
            R.drawable.messi, R.drawable.lewandowski, R.drawable.gerard,
            R.drawable.neymar, R.drawable.jadon, R.drawable.stones,
            R.drawable.mbappe, R.drawable.aspas, R.drawable.joao,
            R.drawable.nico
    };

    private static String[] preview = new String[]{
            "Lionel Andrés Messi born 24 June 1987 is an Argentine professional footballer who plays as a forward and captains both Spanish club Barcelona and the Argentina national team. Often considered as the best player in the world and widely regarded as one of the greatest players of all time, Messi has won a record six Ballon d'Or awards, a record six European Golden Shoes, and in 2020 was named to the Ballon d'Or Dream Team. He has spent his entire professional career with Barcelona, where he has won a club-record 35 trophies, including ten La Liga titles, seven Copa del Rey titles and four UEFA Champions Leagues. A prolific goalscorer and creative playmaker, Messi holds the records for most goals in La Liga (469), a La Liga and European league season (50), most hat-tricks in La Liga (36) and the UEFA Champions League (8), and most assists in La Liga (192), a La Liga and European league season (21) and the Copa América (12). He has scored over 750 senior career goals for club and country, and has the most goals ever by a player for a single club.",
            "Robert Lewandowski born 21 August 1988 is a Polish professional footballer who plays as a striker for Bundesliga club Bayern Munich and is the captain of the Poland national team. He is renowned for his positioning, technique and finishing, and is widely regarded as one of the best strikers in the world, and one of the best players in Bundesliga history. He has scored over 500 senior career goals for club and country. After being the top scorer in the third and second tiers of Polish football with Znicz Pruszków, Lewandowski moved to top-flight Lech Poznan, helping the team win the 2009–10 Ekstraklasa. In 2010, he transferred to Borussia Dortmund, where he won honours including two consecutive Bundesliga titles and the league's top goalscorer award. In 2013, he also featured with Dortmund in the 2013 UEFA Champions League Final. Prior to the start of the 2014–15 season, Lewandowski agreed to join Dortmund's domestic rivals, Bayern Munich, on a free transfer. In Munich, he has won the Bundesliga title in each of his first six seasons. Lewandowski was integral in Bayern's UEFA Champions League win in 2019–20 as part of a treble. He is one of only two players, alongside Johan Cruyff, to achieve the European treble, while being the top scorer in all three competitions.",
            "Gerard Moreno Balagueró, known simply as Gerard born 7 April 1992, is a Spanish professional footballer who plays as a striker for Villarreal CF and the Spain national team. Gerard was never capped for Spain at any youth level. He made his senior debut on 15 October 2019, playing the entire 1–1 draw in Sweden for the UEFA Euro 2020 qualifiers. One month later, for the same competition and also as a starter, he scored his first goal in a 7–0 rout of Malta in Cádiz for the already qualified hosts.On 18 November, he added a brace in the 5–0 victory over Romania.",
            "Neymar da Silva Santos Júnior born 5 February 1992, known as Neymar, is a Brazilian professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the Brazil national team. He is widely regarded as one of the best players in the world.Neymar came into prominence at Santos, where he made his professional debut aged 17. He helped the club win two successive Campeonato Paulista championships, a Copa do Brasil, and the 2011 Copa Libertadores; the latter being Santos' first since 1963. Neymar was twice named the South American Footballer of the Year, in 2011 and 2012, and soon relocated to Europe to join Barcelona. As part of Barcelona's attacking trio with Lionel Messi and Luis Suárez, he won the continental treble of La Liga, the Copa del Rey, and the UEFA Champions League, and finished third for the FIFA Ballon d'Or in 2015 for his performances. He then attained a domestic double in the 2015–16 season. In 2017, Neymar transferred to Paris Saint-Germain in a move worth €222 million, making him the most expensive player ever.In France, Neymar won three league titles, two Coupe de France, and two Coupe de la Ligue, which included a domestic treble and being voted Ligue 1 Player of the Year in his debut season.Neymar helped PSG attain a domestic quadruple in the 2019–20 season, and led the club to its first ever Champions League Final.",
            "Jadon Malik Sancho (born 25 March 2000) is an English professional footballer who plays as a winger for German Bundesliga club Borussia Dortmund and the England national team. A highly technical, creative player, he is known for his trickery, pace and use of feints in one-on-one situations. He came runner-up for the 2019 Kopa Trophy and was nominated to the 40-man shortlist for the 2020 Golden Boy. Previously a youth player with Watford and Manchester City, Sancho signed his first senior contract with Dortmund in 2017. In his second season, he established himself as a first-team regular and was named in the 2018–19 Bundesliga Team of the Season. Ahead of the 2019–20 season, Sancho won his first trophy following the DFL-Supercup victory over Bayern Munich.",
            "John Stones (born 28 May 1994) is an English professional footballer who plays as a centre-back for Premier League club Manchester City and the England national team. Stones began his career with Barnsley, making his first-team debut in the Championship in March 2012 as a 17-year-old. He joined Premier League club Everton for around £3 million in January 2013 and amassed 95 appearances over four seasons. In August 2016, he signed for Manchester City for an initial £47.5 million with add-ons. He won the Premier League in 2018 and 2019, the EFL Cup in 2018, 2019 and 2020, and the FA Cup in 2019 as well. Stones made his senior debut for England in May 2014 after previously being capped by England youth teams at under-19, under-20 and under-21 levels. He was chosen in England's squads for UEFA Euro 2016 and the 2018 FIFA World Cup.",
            "Kylian Mbappé Lottin (born 20 December 1998) is a French professional footballer who plays as a forward for Ligue 1 club Paris Saint-Germain and the France national team. Widely considered as one of the best players in the world, he is known for his dribbling, explosive speed, and clinical finishing. Mbappé began his senior career with Ligue 1 club Monaco, making his professional debut in 2015, aged 16. With them, he won a Ligue 1 title, Ligue 1 Young Player of the Year, and the Golden Boy award. In 2017, he signed for league rivals Paris Saint-Germain on an initial loan, which was made permanent in 2018 in a transfer worth €180 million, making him both the second-most expensive player and most expensive teenager. There, Mbappé won three Ligue 1 titles, two Coupe de France titles, was named Ligue 1 Player of the Year, and has finished as Ligue 1 top scorer twice. He is also the third-highest goalscorer in the club's history.",
            "Iago Aspas Juncal born 1 August 1987 is a Spanish professional footballer who plays as a striker for Celta Vigo and the Spain national team. He has spent most of his career with Celta, appearing in 346 official games across 11 seasons and scoring 152 goals. He made his La Liga debut with the club in 2012 and moved to Liverpool the following year, returning to Celta in 2015. Aspas first appeared with the Spain senior team in 2016. He represented the country at the 2018 World Cup.",
            "João Pedro Cavaco Cancelo (born 27 May 1994) is a Portuguese professional footballer who plays for Premier League club Manchester City and the Portugal national team. Mainly a right back, he can also play as a right winger or a left back. After coming through Benfica's youth academy, Cancelo began playing for the club's reserve side in 2012 and was promoted to the first team two years later. He was subsequently loaned to La Liga club Valencia during the 2014–15 season, with Los Ches making the move permanent in the summer of 2015. Cancelo was on loan to Serie A team Inter Milan during the 2017–18 season, in which he was included in Serie A's Team of the Year. Cancelo's performances sparked the interest of Italian rivals Juventus, who signed him in 2018 for a reported fee of €40.4 million. During his stint with Bianconeri, Cancelo won the league and the Supercoppa Italiana in his first and only season. In 2019, he was signed by English club Manchester City, in a transfer worth an initial €30 million (£27.4 million).",
            "Nico Elvedi (born 30 September 1996) is a Swiss professional footballer who plays as a centre back for Borussia Mönchengladbach and the Switzerland national team. Born in Zürich, Elvedi was a youth player for FC Zürich. He made his Swiss Super League debut on 15 May 2014 in a 1–0 away win against FC Lausanne-Sport playing the full match. Elvedi joined Borussia Mönchengladbach in 2015 for a €4 million transfer fee. He scored his first goal in the Bundesliga during the derby against 1. FC Köln. The match saw Borussia Mönchengladbach win 1–0. Elvedi played for various Swiss youth teams, and made his debut for the senior Switzerland national football team in a friendly 1–2 defeat to Belgium on 28 May 2016. He was included in the Switzerland national football team 23-man squad for the 2018 FIFA World Cup. In May 2019, he played in 2019 UEFA Nations League Finals, where his team finished 4th."
    };

    public static ArrayList<FootballModel> getListData(){
        FootballModel footballModel = null;
        ArrayList<FootballModel> list = new ArrayList<>();
        for (int i=0; i<title.length; i++){
            footballModel = new FootballModel();
            footballModel.setPhoto(thumbnail[i]);
            footballModel.setPlayer_name(title[i]);
            footballModel.setPreview(preview[i]);

            list.add(footballModel);
        }return list;
    }
}
